# Site settings
title: Portfolio Site - Ren Blanding
tagline: "UX/UI Designer for eCommerce and non-profit orgs."
# url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

collections:
  projects:
    output: true
    permalink: /projects/:title

# Social
github: Hakata-jpn
linkedin: blandingr

# Contact
email: "blandingren425@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
sass:
    sass_dir: _sass
    style: compressed

# Build settings
markdown: kramdown
highlighter: rouge
parse_block_html: true
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-archives



exclude: [README.md, node_modules, gruntfile.js, package.json]
