# Site settings
title: Portfolio Site - Ren Blanding
tagline: "UX/UI Designer for eCommerce and non-profit orgs."
# url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

collections:
  projects:
    output: true
    permalink: /projects/:title

# Social
github: Hakata-jpn
linkedin: blandingr

# Contact
email: "blandingren425@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
sass:
    style: compressed

exclude: [README.md, node_modules, gruntfile.js, package.json]
